source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "jekyll-remote-theme"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "kramdown-parser-gfm"
