source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "jekyll-remote-theme"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "jekyll-toc"
gem "jekyll-default-layout"
gem "jekyll-readme-index"
gem "jekyll-optional-front-matter"
gem "jekyll-relative-links"
gem "jekyll-gist"
gem "jekyll-coffeescript"
gem "kramdown-parser-gfm"
